name: app-pipeline
on: push
jobs:

  deploy:
    runs-on: alpine-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_ACCESS_TOKEN}

      - name: PrepareReg Names
        id: read-docker-image-identifiers
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
